"""initial migration

Revision ID: 9d1e6417f035
Revises: 
Create Date: 2024-07-08 17:26:03.721455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d1e6417f035'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anuncio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_anuncio_user', 'user', ['user_id'], ['id'])
        batch_op.drop_column('foto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anuncio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint('fk_anuncio_user', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###
